
#define EEPROM_SIZE 0x001000
#define EEPROM_ADDRESS_SETTINGS1 00
#define EEPROM_ADDRESS_SETTINGS2 25
#define EEPROM_ADDRESS_SETTINGS3 50
#define EEPROM_ADDRESS_SETTINGS4 75
#define EEPROM_ADDRESS_SETTINGS5 100
#define EEPROM_ADDRESS_ODO 125
#define EEPROM_ADDRESS_BLE_LOCK_FORCED 200
#define EEPROM_ADDRESS_BRAKE_MAX_PRESSURE 225
